spring:
  application:
    name: databaseclient
  r2dbc:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

